<a href="https://colab.research.google.com/github/ny0172011-hub/Leetcode-Solutions/blob/main/Copy_of_First.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [6]:
# loading the dataset to the pandas dataframe
credit_card_data=pd.read_csv('/content/creditcard.csv.zip')

In [5]:
import zipfile

print(zipfile.is_zipfile("/content/creditcard.csv.zip"))

True

In [4]:
import os

os.listdir("/content")

['.config', 'creditcard.csv.zip', 'sample_data']

In [ ]:
# .head function se first 5 rows print hote hain
# .tail function se last 5 rows print hote hain

In [7]:
credit_card_data.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [8]:
credit_card_data.tail()

            Time         V1         V2  ...       V28  Amount  Class
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[5 rows x 31 columns]

In [9]:
#dataset information
# null values means missing values
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [11]:
# to check the number of missing values in each column
credit_card_data.isnull

<bound method DataFrame.isnull of             Time         V1         V2  ...       V28  Amount  Class
0            0.0  -1.359807  -0.072781  ... -0.021053  149.62      0
1            0.0   1.191857   0.266151  ...  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  ... -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  ...  0.061458  123.50      0
4            2.0  -1.158233   0.877737  ...  0.215153   69.99      0
...          ...        ...        ...  ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[284807 rows x 31 columns]>

In [12]:
# we have two classes class 0 and class 1
# class 0=legit transaction and class 1 is fraud transaction


# distribution of legit transactions and fraudlent transactions

credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [ ]:
# there are 284315 legit transactions and 492 fraud transactions
# so our model will not be able to predict the fraud transactions because
# if we find accuracy on the basis of total data our model will always predit legit transaction

In [14]:
# now we are going to separate the data for analysis
# we will make two variable one variable will store legit data
# and 2nd one will store fraud data
legit=credit_card_data[credit_card_data.Class==0]
fraud=credit_card_data[credit_card_data.Class==1]

In [16]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [18]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [19]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [20]:
# we can compare the values for both transactions
credit_card_data.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0      94838.202258  0.008258 -0.006271  ... -0.000295 -0.000131   88.291022
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

In [22]:
# as there is a very large legit value so we need to take the sample dataset of legit data
legitSample=legit.sample(n=492)

In [23]:
# we will concatnate the two dataset
new_dataset=pd.concat([legitSample,fraud],axis=0)
new_dataset.head()

            Time        V1        V2  ...       V28  Amount  Class
165855  117709.0  1.717441 -0.298065  ... -0.049176  144.16      0
187581  127591.0  1.939183  0.012077  ... -0.072298   59.70      0
247666  153650.0  2.117504 -1.414776  ... -0.048639    3.20      0
66359    52009.0  1.102097  0.364046  ...  0.016213   86.43      0
1735      1346.0 -0.471003  1.065758  ...  0.012873    9.78      0

[5 rows x 31 columns]

In [24]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [25]:
new_dataset.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0      91290.172764  0.158887 -0.096561  ... -0.000196 -0.014269   85.561992
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

In [29]:
# splitting the datasets into features and targets
X=new_dataset.drop(columns='Class',axis=1);
Y=new_dataset['Class']
print(X)
print(Y)

            Time        V1        V2  ...       V27       V28  Amount
165855  117709.0  1.717441 -0.298065  ... -0.048346 -0.049176  144.16
187581  127591.0  1.939183  0.012077  ... -0.055003 -0.072298   59.70
247666  153650.0  2.117504 -1.414776  ...  0.047705 -0.048639    3.20
66359    52009.0  1.102097  0.364046  ... -0.066065  0.016213   86.43
1735      1346.0 -0.471003  1.065758  ...  0.371798  0.012873    9.78
...          ...       ...       ...  ...       ...       ...     ...
279863  169142.0 -1.927883  1.125653  ...  0.292680  0.147968  390.00
280143  169347.0  1.378559  1.289381  ...  0.389152  0.186637    0.76
280149  169351.0 -0.676143  1.126366  ...  0.385107  0.194361   77.89
281144  169966.0 -3.113832  0.585864  ...  0.884876 -0.253700  245.00
281674  170348.0  1.991976  0.158476  ...  0.002988 -0.015309   42.53

[984 rows x 30 columns]
165855    0
187581    0
247666    0
66359     0
1735      0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [30]:
# split the data into training  data and test data
# for training the model

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [33]:
print(X.shape,X_test.shape,X_train.shape)

(984, 30) (197, 30) (787, 30)

In [34]:
# model training
model=LogisticRegression()

In [35]:
# training the logistic regression model with the training data
model.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [37]:
# to find the performance of our model
# Accuracy
# Accuracy on training data
X_train_prediction=model.predict(X_train)
trainingDataAccuracy=accuracy_score(X_train_prediction,Y_train)

In [38]:
print('Accuracy on training data:',trainingDataAccuracy)

Accuracy on training data: 0.9466327827191868

In [41]:
# accuracy  on testdata
X_test_prediction=model.predict(X_test)
testDataAccuracy=accuracy_score(X_test_prediction,Y_test)
print('Accuracy on test data:',testDataAccuracy)

Accuracy on test data: 0.949238578680203